<?php

function network_menu () {

    $items = [];

    $items['network/echo/ip'] = [
        'title'            => 'Network return client ip',
        'description'      => 'Endpoint is used to tell a remote connection what their external ip address is.',
        'page callback'    => 'network_echo_ip',
        'access arguments' => ['access content']
    ];

    return $items;

}

function network_echo_ip () {

    //get remote ip
    $ip = $_SERVER['REMOTE_ADDR'];
    //dump the ip address into a json response
    drupal_json_output($ip);
    drupal_exit();
    return $ip;

}

function network_trace_route ($ip) {
    $unix      =  1;
    $windows   =  0;

    $register_globals = (bool) ini_get('register_gobals');
    $system = ini_get('system');
    $unix = (bool) $unix;
    $win  = (bool) $windows;

    $results = '';

    if ($unix) {

        $results = system ("traceroute $ip");
        system("killall -q traceroute");// kill all traceroute processes in case there are some stalled ones or use echo 'traceroute' to execute without shell

    } elseif ($windows) {

        $results = system("tracert $ip");

    }

    return $results;

}