<?php

function turret_init () {

}

function turret_menu () {

    $items = [];

    $items['admin/machine/turret'] = [
        'title'            => 'Turret',
        'description'      => 'Configure Machine Gun Turrets',
        'page callback'    => 'turret_admin_form',
        'page arguments'   => [],
        'access arguments' => ['administer devices'],
        'file'             => 'turret.admin.inc'
    ];

    return $items;

}

function turret_endpoints () {
    $endpoints = [];

    $endpoints['/v1/rest/turret/register'] = [
        'description'      => 'A turret touches this endpoint to register itself with Machine Gun.',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_register_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/claim'] = [
        'description'      => 'A turret may be claimed by a logged in user by its turret_id',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_claim_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/release'] = [
        'description'      => 'A user may release a previously claimed turret by turret_id.',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_release_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/config-form'] = [
        'description'      => 'Get a turret\'s configuration form',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_config_form_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/configure'] = [
        'description'      => 'Push values here to configure your turret, the config-form should have given you all the key value pairs this turret understands.',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_configure_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/status'] = [
        'description'      => 'Queries a turret for it\'s current status object.',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_status_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/connect'] = [
        'description'      => 'A turret touches this endpoint when it is available and active.',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_connect_endpoint',
        'file'             => 'turret.api.inc'
    ];

    $endpoints['/v1/rest/turret/disconnect'] = [
        'description'      => 'A turret touches this endpoint when it is no longer available (likely shutting down)',
        'access arguments' => ['access content'],//@todo: create a turret access param
        'handler'          => 'turret_disconnect_endpoint',
        'file'             => 'turret.api.inc'
    ];

    return $endpoints;

}

/**
 * Implements hook_events
 */
function turret_events () {

    $events = [];

    $events['connect'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_connect_event'
    ];

    $events['disconnect'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_disconnect_event'
    ];

    $events['authenticate'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_authenticate_event'
    ];

    $events['status'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_status_event'
    ];

    $events['message'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_message_event'
    ];

    $events['timeout'] = [
        'source' => 'turret:*',
        'callback' => 'turret_on_timeout_event'
    ];

    return $events;

}

function turret_on_connect_event (&$event) {
    //when a turret connects to machine gun

    $event['data']['key2'] = 'value2';

}

function turret_on_disconnect_event (&$event) {
    //when a turret disconnects from machine gun

}

function turret_on_authenticate_event (&$event) {
    //when a turret tries to authenticate
}

function turret_on_status_event (&$event) {

}

function turret_on_message_event (&$param) {
    //all in-bound turret communication should go through this endpoint
    //this will be handled as a socket.io callback

}